version: '3'
services:
  customers:
    image: moov/customers:v0.4.1
    ports:
      - "8087:8087"
      - "9097:9097"
    environment:
      FED_ENDPOINT: 'http://fed:8086'
      # The transit key matches customers.accounts.decryptor.symmetric.keyURI in examples/config.yaml
      TRANSIT_LOCAL_BASE64_KEY: 'base64key://MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='
      PAYGATE_ENDPOINT: 'http://paygate:8082'
      WATCHMAN_ENDPOINT: 'http://watchman:8084'
      VIRTUAL_HOST: 'customers-dev.gnu.lv'
      #VIRTUAL_PATH: '/customers'
      VIRTUAL_PORT: '8087'
      LETSENCRYPT_HOST: 'customers-dev.gnu.lv'
    depends_on:
      - fed
      # - paygate
      - watchman

  customers_wrapper:
    image: marcnuri/port-forward
    environment:
      REMOTE_HOST: 'customers'
      REMOTE_PORT: '9097'
      VIRTUAL_P0RT: '9097'
      VIRTUAL_HOST: 'customers-admin-dev.gnu.lv'
      LETSENCRYPT_HOST: 'customers-admin-dev.gnu.lv'
  fed:
    image: moov/fed:v0.5.1
    ports:
      - "8086:8086"
      - "9096:9096"
    environment:
      FEDACH_DATA_PATH: './data/fed/FedACHdir.txt'
      FEDWIRE_DATA_PATH: './data/fed/fpddir.txt'
  watchman:
    image: moov/watchman:static
    ports:
      - "8084:8084"
      - "9094:9094"
  ftp:
    image: moov/fsftp:v0.2.0
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    volumes:
      - "./testdata/ftp-server:/data"
    command:
      - "-host=0.0.0.0"
      - "-root=/data"
      - "-user=admin"
      - "-pass=123456"
      - "-passive-ports=30000-30009"
  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    volumes:
      - "./testdata/sftp-server:/home/demo/upload"
    command:
      - "demo:password:::upload"
  smtp:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '1025:1025'
      - '4436:4436'
      - '4437:4437'

  paygate:
    image: moov/paygate:v0.8.0
    ports:
      - "8082:8082"
      - "9092:9092"
    command: ["-config=/conf/config.yaml"]
    expose:
      - "8082"
      - "9092"
    environment:
      CUSTOMERS_ENDPOINT: 'http://customers:8087'
      #ACH_FILE_MAX_LINES: 20 # upload files when they're a lot smaller than the 10k default
      #ACH_FILE_TRANSFER_INTERVAL: 30s # Merge and Upload files this often
      VIRTUAL_HOST: 'paygate-dev.gnu.lv'
      VIRTUAL_PORT: '8082'
      #VIRTUAL_PATH: '/paygate'
      LETSENCRYPT_HOST: 'paygate-dev.gnu.lv'
    depends_on:
      - customers
    volumes:
      - "./data:/data"
      - "./conf/:/conf/"

  paygate_wrapper:
    image: marcnuri/port-forward
    environment:
      REMOTE_HOST: 'paygate'
      REMOTE_PORT: '9092'
      VIRTUAL_P0RT: '9092'
      VIRTUAL_HOST: 'paygate-admin-dev.gnu.lv'
      LETSENCRYPT_HOST: 'paygate-admin-dev.gnu.lv'
  nginx-proxy:
    image: jwilder/nginx-proxy #christhomas/nginx-proxy:alpine ##
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /etc/docker/compose/paygate/htpasswd/:/etc/nginx/htpasswd/
      - ./vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./paygate-nginx.conf:/etc/nginx/conf.d/paygate-nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/gunspring:/var/www/gunspring
      - /etc/nginx/sites-available/gunspring:/etc/nginx/conf.d/gunspring.conf

    restart: always
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
volumes:
  conf:
  html:
  dhparam:
  certs:
  # vhosts:
